"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { collection, getDocs, doc, deleteDoc, query, orderBy } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useAuth } from "@/components/providers/AuthProvider";
import { useToast } from "@/components/providers/ToastProvider";
import { 
  ProblemStatement, 
  getAllProblemStatementsAdmin, 
  updateProblemStatus, 
  deleteProblemStatement 
} from "@/lib/problem-statements";
import { 
  FileCode2, 
  ArrowLeft, 
  Plus, 
  Sparkles, 
  Search, 
  Filter, 
  CheckCircle2, 
  Clock, 
  Archive, 
  Eye, 
  Edit3, 
  Trash2, 
  Users, 
  Layers, 
  Globe, 
  Loader2,
  ExternalLink,
  ShieldCheck,
  Send
} from "lucide-react";

export default function AdminProblemStatementsPage() {
  const { user, firebaseUser } = useAuth();
  const { success, error } = useToast();

  const [problems, setProblems] = useState<ProblemStatement[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [searchQuery, setSearchQuery] = useState("");
  const [processingId, setProcessingId] = useState<string | null>(null);

  // Gemini AI Generator Modal state
  const [aiModalOpen, setAiModalOpen] = useState(false);
  const [generatingAi, setGeneratingAi] = useState(false);
  const [aiForm, setAiForm] = useState({
    domain: "Software Engineering",
    industry: "Enterprise SaaS & Cloud",
    topic: "Real-Time Telemetry & Fault Recovery Architecture",
    targetUsers: "DevOps teams and site reliability engineers",
    difficulty: "MEDIUM" as const,
    location: "India / Global",
    requiredTech: "React, Node.js, TypeScript, Docker, Prometheus",
    organization: "SC TECH Original Challenge",
    additionalRequirements: "Must support low-latency metrics ingestion and automated alerts.",
  });

  const loadProblems = async () => {
    setLoading(true);
    try {
      const token = await firebaseUser?.getIdToken();
      const list = await getAllProblemStatementsAdmin(statusFilter, token);
      setProblems(list);
    } catch (err) {
      console.error("Error loading problem statements:", err);
      error("Failed to load problem statements");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadProblems();
  }, [statusFilter, firebaseUser]);

  const handleStatusChange = async (id: string, newStatus: ProblemStatement["status"]) => {
    if (!firebaseUser?.uid) return;
    setProcessingId(id);
    try {
      const token = await firebaseUser.getIdToken();
      const ok = await updateProblemStatus(id, newStatus, firebaseUser.uid, token);
      if (ok) {
        success(`Status updated to ${newStatus}`);
        setProblems(problems.map((p) => (p.id === id ? { ...p, status: newStatus } : p)));
      } else {
        error("Status update failed");
      }
    } catch {
      error("Network error");
    } finally {
      setProcessingId(null);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to permanently delete this problem statement?")) return;
    if (!firebaseUser?.uid) return;
    try {
      const token = await firebaseUser.getIdToken();
      const ok = await deleteProblemStatement(id, firebaseUser.uid, token);
      if (ok) {
        setProblems(problems.filter((p) => p.id !== id));
        success("Problem statement deleted successfully");
      }
    } catch {
      error("Failed to delete problem statement");
    }
  };

  const handleAiGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setGeneratingAi(true);
    try {
      const token = await firebaseUser?.getIdToken();
      const res = await fetch("/api/ai/generate-problem-statement", {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify(aiForm),
      });
      const data = await res.json();
      if (res.ok && data.problem) {
        success("Problem Statement generated by Gemini AI! Stored as DRAFT.");
        setAiModalOpen(false);
        await loadProblems();
        window.location.href = `/admin/problem-statements/create?aiData=${encodeURIComponent(JSON.stringify(data.problem))}`;
      } else {
        error(data.error || "Generation failed");
      }
    } catch {
      error("Failed to generate with Gemini AI");
    } finally {
      setGeneratingAi(false);
    }
  };

  const filteredProblems = problems.filter((item) => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return (
      item.title?.toLowerCase().includes(q) ||
      item.domain?.toLowerCase().includes(q) ||
      item.organization?.toLowerCase().includes(q) ||
      item.requiredSkills?.some((s) => s.toLowerCase().includes(q))
    );
  });

  const stats = {
    total: problems.length,
    published: problems.filter((p) => p.status === "PUBLISHED").length,
    drafts: problems.filter((p) => p.status === "DRAFT").length,
    pending: problems.filter((p) => p.status === "PENDING_REVIEW").length,
  };

  return (
    <div className="min-h-screen bg-[#0B0F19] text-slate-100 p-6 lg:p-10 space-y-8 max-w-7xl mx-auto">
      
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-800">
        <div className="space-y-1">
          <Link href="/admin" className="inline-flex items-center gap-1.5 text-xs text-blue-400 hover:text-blue-300 font-semibold mb-2">
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Admin Panel</span>
          </Link>
          <h1 className="text-2xl sm:text-3xl font-black text-white flex items-center gap-3">
            <FileCode2 className="w-7 h-7 text-blue-400" />
            <span>Real-World Problem Statements Architecture</span>
          </h1>
          <p className="text-xs text-slate-400">
            Create, curate, and review SIH-style problem statements with Gemini AI integration.
          </p>
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          <button
            onClick={() => setAiModalOpen(true)}
            className="px-5 py-2.5 rounded-2xl bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-500 hover:to-purple-500 text-white font-bold text-xs shadow-lg shadow-purple-600/20 flex items-center gap-2 cursor-pointer"
          >
            <Sparkles className="w-4 h-4 text-amber-300" />
            <span>Generate with Gemini AI</span>
          </button>

          <Link
            href="/admin/problem-statements/create"
            className="px-5 py-2.5 rounded-2xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs shadow-lg shadow-blue-600/30 flex items-center gap-2"
          >
            <Plus className="w-4 h-4" />
            <span>Create Statement</span>
          </Link>
        </div>
      </div>

      {/* 4 Stats Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="p-5 rounded-3xl bg-slate-900/90 border border-slate-800 space-y-1">
          <span className="text-xs font-semibold text-slate-400">Total Statements</span>
          <div className="text-3xl font-black text-white">{stats.total}</div>
          <p className="text-[11px] text-slate-500">In database</p>
        </div>

        <div className="p-5 rounded-3xl bg-slate-900/90 border border-emerald-500/30 space-y-1">
          <span className="text-xs font-semibold text-emerald-400">Published to Students</span>
          <div className="text-3xl font-black text-emerald-300">{stats.published}</div>
          <p className="text-[11px] text-emerald-400/80">Active on /problem-statements</p>
        </div>

        <div className="p-5 rounded-3xl bg-slate-900/90 border border-amber-500/30 space-y-1">
          <span className="text-xs font-semibold text-amber-400">Drafts</span>
          <div className="text-3xl font-black text-amber-300">{stats.drafts}</div>
          <p className="text-[11px] text-slate-500">Under preparation</p>
        </div>

        <div className="p-5 rounded-3xl bg-slate-900/90 border border-slate-800 space-y-1">
          <span className="text-xs font-semibold text-blue-400">Pending Review</span>
          <div className="text-3xl font-black text-blue-300">{stats.pending}</div>
          <p className="text-[11px] text-slate-500">Awaiting approval</p>
        </div>
      </div>

      {/* Filter Tabs & Search */}
      <div className="flex flex-col sm:flex-row gap-4 items-center justify-between">
        <div className="flex flex-wrap items-center gap-2 text-xs">
          {["ALL", "PUBLISHED", "DRAFT", "PENDING_REVIEW", "CLOSED", "ARCHIVED"].map((st) => (
            <button
              key={st}
              onClick={() => setStatusFilter(st)}
              className={`px-4 py-2 rounded-xl font-semibold transition ${
                statusFilter === st
                  ? "bg-blue-600 text-white shadow-md shadow-blue-600/30"
                  : "bg-slate-900 border border-slate-800 text-slate-400 hover:text-slate-200"
              }`}
            >
              {st.replace("_", " ")}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-80">
          <Search className="w-4 h-4 text-slate-500 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by title, domain, or skills..."
            className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-10 pr-4 py-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-blue-500"
          />
        </div>
      </div>

      {/* Problem Statements Table */}
      {loading ? (
        <div className="py-20 text-center text-slate-400 flex items-center justify-center gap-3">
          <Loader2 className="w-6 h-6 animate-spin text-blue-500" />
          <span>Loading problem statements...</span>
        </div>
      ) : filteredProblems.length === 0 ? (
        <div className="p-16 rounded-3xl bg-slate-900/40 border border-slate-800 text-center space-y-4">
          <FileCode2 className="w-10 h-10 text-slate-600 mx-auto" />
          <h3 className="text-base font-bold text-white">No problem statements found</h3>
          <p className="text-xs text-slate-400 max-w-sm mx-auto">
            Click &quot;Generate with Gemini AI&quot; or &quot;Create Statement&quot; to add your first real-world challenge.
          </p>
        </div>
      ) : (
        <div className="p-6 rounded-3xl bg-slate-900/90 border border-slate-800 shadow-xl overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400 uppercase tracking-wider text-[10px] pb-3">
                <th className="pb-3 font-semibold">Problem Title & Domain</th>
                <th className="pb-3 font-semibold">Organization / Source</th>
                <th className="pb-3 font-semibold">Difficulty</th>
                <th className="pb-3 font-semibold">Status</th>
                <th className="pb-3 font-semibold">Submissions</th>
                <th className="pb-3 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800 text-slate-200">
              {filteredProblems.map((p) => (
                <tr key={p.id} className="hover:bg-slate-800/40 transition">
                  <td className="py-4 max-w-sm">
                    <div className="font-bold text-white leading-snug line-clamp-1">{p.title}</div>
                    <div className="text-[11px] text-blue-400 font-semibold mt-0.5">
                      {p.domain} • Team: {p.teamSizeMin}-{p.teamSizeMax}
                    </div>
                  </td>
                  <td className="py-4">
                    <span className="font-medium text-slate-300">{p.organization || "SC TECH Original"}</span>
                    <span className="block text-[10px] text-slate-500">{p.organizationType}</span>
                  </td>
                  <td className="py-4">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                      p.difficulty === "HARD" ? "bg-rose-500/20 text-rose-300" :
                      p.difficulty === "MEDIUM" ? "bg-amber-500/20 text-amber-300" :
                      "bg-emerald-500/20 text-emerald-300"
                    }`}>
                      {p.difficulty}
                    </span>
                  </td>
                  <td className="py-4">
                    <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                      p.status === "PUBLISHED" ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30" :
                      p.status === "DRAFT" ? "bg-amber-500/20 text-amber-300 border border-amber-500/30" :
                      p.status === "PENDING_REVIEW" ? "bg-blue-500/20 text-blue-300 border border-blue-500/30" :
                      "bg-slate-800 text-slate-400"
                    }`}>
                      {p.status.replace("_", " ")}
                    </span>
                  </td>
                  <td className="py-4">
                    <Link
                      href={`/admin/problem-statements/${p.id}/submissions`}
                      className="inline-flex items-center gap-1.5 text-xs text-indigo-400 hover:text-indigo-300 font-bold"
                    >
                      <Users className="w-3.5 h-3.5" />
                      <span>Submissions</span>
                    </Link>
                  </td>
                  <td className="py-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      {p.status !== "PUBLISHED" ? (
                        <button
                          type="button"
                          onClick={() => handleStatusChange(p.id!, "PUBLISHED")}
                          disabled={processingId === p.id}
                          className="px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-[11px] font-bold shadow transition"
                        >
                          Publish
                        </button>
                      ) : (
                        <button
                          type="button"
                          onClick={() => handleStatusChange(p.id!, "DRAFT")}
                          disabled={processingId === p.id}
                          className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-amber-600 text-slate-300 hover:text-white text-[11px] font-bold transition"
                        >
                          Unpublish
                        </button>
                      )}

                      <Link
                        href={`/admin/problem-statements/${p.id}/edit`}
                        className="p-1.5 text-slate-400 hover:text-white transition"
                        title="Edit Statement"
                      >
                        <Edit3 className="w-4 h-4" />
                      </Link>

                      <button
                        type="button"
                        onClick={() => handleDelete(p.id!)}
                        className="p-1.5 text-slate-500 hover:text-rose-400 transition"
                        title="Delete Statement"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Gemini AI Generation Modal */}
      <AnimatePresence>
        {aiModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 max-w-xl w-full shadow-2xl space-y-6"
            >
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-2.5">
                  <Sparkles className="w-5 h-5 text-purple-400" />
                  <h3 className="text-base font-black text-white">Generate SIH Problem with Gemini AI</h3>
                </div>
                <button
                  onClick={() => setAiModalOpen(false)}
                  className="text-slate-400 hover:text-white text-xs"
                >
                  ✕
                </button>
              </div>

              <form onSubmit={handleAiGenerate} className="space-y-4 text-xs">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-slate-400 block mb-1">Domain</label>
                    <input
                      type="text"
                      value={aiForm.domain}
                      onChange={(e) => setAiForm({ ...aiForm, domain: e.target.value })}
                      className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200"
                    />
                  </div>
                  <div>
                    <label className="text-slate-400 block mb-1">Difficulty</label>
                    <select
                      value={aiForm.difficulty}
                      onChange={(e) => setAiForm({ ...aiForm, difficulty: e.target.value as any })}
                      className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200"
                    >
                      <option value="EASY">EASY</option>
                      <option value="MEDIUM">MEDIUM</option>
                      <option value="HARD">HARD</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="text-slate-400 block mb-1">Problem Topic / Challenge Concept</label>
                  <input
                    type="text"
                    value={aiForm.topic}
                    onChange={(e) => setAiForm({ ...aiForm, topic: e.target.value })}
                    placeholder="e.g. AI-Powered Healthcare Diagnostics or Smart Grid Power Optimization"
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200"
                    required
                  />
                </div>

                <div>
                  <label className="text-slate-400 block mb-1">Required Tech & Skills</label>
                  <input
                    type="text"
                    value={aiForm.requiredTech}
                    onChange={(e) => setAiForm({ ...aiForm, requiredTech: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200"
                  />
                </div>

                <div>
                  <label className="text-slate-400 block mb-1">Target Users / Stakeholders</label>
                  <input
                    type="text"
                    value={aiForm.targetUsers}
                    onChange={(e) => setAiForm({ ...aiForm, targetUsers: e.target.value })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200"
                  />
                </div>

                <div>
                  <label className="text-slate-400 block mb-1">Additional Constraints / Guidelines</label>
                  <textarea
                    value={aiForm.additionalRequirements}
                    onChange={(e) => setAiForm({ ...aiForm, additionalRequirements: e.target.value })}
                    rows={2}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200"
                  />
                </div>

                <div className="pt-3 border-t border-slate-800 flex items-center justify-end gap-3">
                  <button
                    type="button"
                    onClick={() => setAiModalOpen(false)}
                    className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 font-bold"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={generatingAi}
                    className="px-6 py-2 rounded-xl bg-gradient-to-r from-violet-600 to-purple-600 text-white font-bold flex items-center gap-2 disabled:opacity-50"
                  >
                    {generatingAi ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        <span>Generating Architecture...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 text-amber-300" />
                        <span>Generate with Gemini</span>
                      </>
                    )}
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
}
